name: build-app
on:
  push:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: test
        run: ./gradlew test
      - name: "Create Keystore folder"
        run: |
          mkdir .keys
      - name: "Generate Keystore File"
        id: keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: '.keys/h300s.keystore'
          encodedString: ${{ secrets.SIGN_KEY }}
      - name: "List file"
        env:
          KEYSTORE_FILE: ${{ steps.keystore.outputs.filePath }}
        run: ls -l ${KEYSTORE_FILE}
      - name: "Build Signed APK"
        id: "apk"
        env:
          KEYSTORE_FILE: ${{ steps.keystore.outputs.filePath }}
          KEYALIAS: ${{secrets.KEYALIAS}}
          MYAPP_RELEASE_KEY_PASSWORD: ${{secrets.MYAPP_RELEASE_KEY_PASSWORD}}
          MYAPP_RELEASE_STORE_PASSWORD: ${{secrets.MYAPP_RELEASE_STORE_PASSWORD}}
        run: |
          ./gradlew assembleRelease
          ls -l ./app/build/outputs/apk/release
          echo "::set-output name=path::./app/build/outputs/apk/release/apk-release.apk"
      - name: Mark Build Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.date.outputs.date }}
      - name: "Upload artifact"
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: ${{ steps.apk.outputs.path }}
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release APK ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}