name: pr
on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: test
        run: ./gradlew test
      - name: build
        run: ./gradlew build
      - name: Assemble Release Bundle
         run: |
            ./gradlew bundleRelease