name: pr
on:
  push:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: test
        run: ./gradlew test
      - name: Build Signed APK
        uses: victorbnl/build-signed-apk@main
        with:
          keystore: ${{ secrets.SIGN_KEY }}
          keystore_password: ${{ secrets.MYAPP_RELEASE_STORE_PASSWORD }}
          key_alias: ${{ secrets.KEYALIAS }}
          key_password: ${{ secrets.MYAPP_RELEASE_KEY_PASSWORD }}