name: build-app
on:
  push:
    branches: [dev]

jobs:

  file_gen:
    runs-on: ubuntu-latest
    steps:
      - id: "step1"
        name: "Generate a file"
        run: |
          echo "HELLO" > ./hello.txt
      - uses: actions/upload-artifact@master
        with:
          name: hello.txt
          path: hello

  file_gen2:
    runs-on: ubuntu-latest
    steps:
      - id: "step1"
        name: "Generate a file"
        run: |
          echo "HELLO2" > ./hello2.txt
      - uses: actions/upload-artifact@master
        with:
          name: hello2.txt
          path: hello

  file_read:
    needs: file_gen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: hello.txt
          path: .
      - uses: actions/download-artifact@master
          with:
            name: hello2.txt
            path: .
      - id: step1
        env:
          file: ${{ needs.file_gen.outputs.path }}
          contents: ${{ needs.file_gen.outputs.contents }}
        run: |
          ls -l .
          cat ./hello.txt
          cat ./hello2.txt