name: build-app
on:
  push:
    branches: [dev]

jobs:

  file_gen:
    runs-on: ubuntu-latest
    steps:
      - id: "step1"
        name: "Generate a file"
        run: |
          echo "HELLO" > ./hello.txt
          echo "::set-output name=path::hello.txt"
      - uses: actions/upload-artifact@master
        with:
          name: file
          path: hello.txt

  file_read:
    needs: file_gen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: file
          path: hello.txt
      - id: step1
        env:
          file: ${{ needs.file_gen.outputs.path }}
          contents: ${{ needs.file_gen.outputs.contents }}
        run: |
         cat hello.txt