name: build-app
on:
  push:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: testLint
        run: ./gradlew lint

#      - name: test
#        run: ./gradlew test

      - name: Bump Version
        run: |
          sed -i -e "s/versionCode.*/versionCode $(date +'%Y%m%d')/g" -e "s/versionName.*/versionName \"v$(date +'%Y-%m-%d')\"/g"  ./app/build.gradle

      - name: "Commit version Bump"
        uses: EndBug/add-and-commit@v7
        with:
          add: './app/build.gradle'
          commit_message: "Version Bump"
          author_name: "Autobuild Bot"

      - name: "Test Build APK"
        id: "apk_unsigned"
        run: |
          ./gradlew assembleRelease
          ls -l ./app/build/outputs/apk/release